language: node_js
node_js:
  - '10'
branches:
  only:
    - source
cache:
  yarn: true
script:
  - git config --global user.name "sangrialab"
  - git config --global user.email "wxrkyd123@163.com"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - yarn && GIT_USER="${GH_NAME}" yarn deploy